apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spinal-tap
  labels:
    app: spinal-tap
spec:
  rules:
  - host: spinal-tap.slac.stanford.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spinal-tap
            port:
              number: 8888
