apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spinal-tap-data
  labels:
    app: spinal-tap
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sdf-data-neutrino  # Replace with your facility's storageClass
